-- MySQL Script generated by MySQL Workbench
-- Thu 15 Apr 2021 09:54:57 AM
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema workorder
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema workorder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `workorder` DEFAULT CHARACTER SET latin1 ;
USE `workorder` ;

-- -----------------------------------------------------
-- Table `workorder`.`MANAGER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`MANAGER` (
  `ID_NO` VARCHAR(10) NOT NULL,
  `Mname` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_NO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`EMPLOYEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`EMPLOYEE` (
  `ID_NO` VARCHAR(10) NOT NULL,
  `SIN` VARCHAR(9) NULL DEFAULT NULL,
  `Name` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_NO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`WORKSTATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`WORKSTATION` (
  `Station_ID` INT(11) NOT NULL,
  `W_name` VARCHAR(20) NULL DEFAULT NULL,
  `M_ID` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`Station_ID`),
  INDEX `M_ID` (`M_ID` ASC) VISIBLE,
  CONSTRAINT `WORKSTATION_ibfk_1`
    FOREIGN KEY (`M_ID`)
    REFERENCES `workorder`.`MANAGER` (`ID_NO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`ASSIGNS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`ASSIGNS` (
  `M_ID` VARCHAR(10) NOT NULL,
  `E_ID` VARCHAR(10) NOT NULL,
  `Station_ID` INT(11) NOT NULL,
  PRIMARY KEY (`M_ID`, `E_ID`, `Station_ID`),
  INDEX `E_ID` (`E_ID` ASC) VISIBLE,
  INDEX `Station_ID` (`Station_ID` ASC) VISIBLE,
  CONSTRAINT `ASSIGNS_ibfk_1`
    FOREIGN KEY (`M_ID`)
    REFERENCES `workorder`.`MANAGER` (`ID_NO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ASSIGNS_ibfk_2`
    FOREIGN KEY (`E_ID`)
    REFERENCES `workorder`.`EMPLOYEE` (`ID_NO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ASSIGNS_ibfk_3`
    FOREIGN KEY (`Station_ID`)
    REFERENCES `workorder`.`WORKSTATION` (`Station_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`REPORT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`REPORT` (
  `Report_ID` INT(11) NOT NULL,
  `Time_Period` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Report_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`AVAILABLE_WORK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`AVAILABLE_WORK` (
  `Report_ID` INT(11) NOT NULL,
  `Station_ID` INT(11) NOT NULL,
  `E_ID` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Report_ID`, `Station_ID`, `E_ID`),
  INDEX `Station_ID` (`Station_ID` ASC) VISIBLE,
  INDEX `E_ID` (`E_ID` ASC) VISIBLE,
  CONSTRAINT `AVAILABLE_WORK_ibfk_4`
    FOREIGN KEY (`Station_ID`)
    REFERENCES `workorder`.`WORKSTATION` (`Station_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `AVAILABLE_WORK_ibfk_5`
    FOREIGN KEY (`Report_ID`)
    REFERENCES `workorder`.`REPORT` (`Report_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `AVAILABLE_WORK_ibfk_6`
    FOREIGN KEY (`E_ID`)
    REFERENCES `workorder`.`EMPLOYEE` (`ID_NO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`BEVELING_STATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`BEVELING_STATION` (
  `Station_ID` INT(11) NOT NULL,
  `edge_type` VARCHAR(20) NOT NULL,
  `BEVEL_SIZE` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Station_ID`, `edge_type`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`Bevel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`Bevel` (
  `Bevel_size` INT(11) NULL DEFAULT NULL,
  `Bevel_Type` VARCHAR(20) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`CUSTOMER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`CUSTOMER` (
  `Customer_ID` VARCHAR(10) NOT NULL,
  `Cname` VARCHAR(20) NULL DEFAULT NULL,
  `Address` VARCHAR(20) NULL DEFAULT NULL,
  `Phone_Number` VARCHAR(12) NULL DEFAULT NULL,
  PRIMARY KEY (`Customer_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`CUTTING_STATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`CUTTING_STATION` (
  `Station_ID` INT(11) NOT NULL,
  `cut_type` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`Station_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`EDGING_STATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`EDGING_STATION` (
  `Station_ID` INT(11) NOT NULL,
  `edge_type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Station_ID`, `edge_type`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`EQUIPMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`EQUIPMENT` (
  `Serial_No` VARCHAR(10) NOT NULL,
  `Station_No` INT(11) NULL DEFAULT NULL,
  `E_Name` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`Serial_No`),
  INDEX `Station_No` (`Station_No` ASC) VISIBLE,
  CONSTRAINT `EQUIPMENT_ibfk_2`
    FOREIGN KEY (`Station_No`)
    REFERENCES `workorder`.`WORKSTATION` (`Station_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`HOLE_CUTTING_STATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`HOLE_CUTTING_STATION` (
  `Station_ID` INT(11) NOT NULL,
  `Hole_Size` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Station_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`LAMINATING_STATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`LAMINATING_STATION` (
  `Station_ID` INT(11) NOT NULL,
  `laminant_type` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`Station_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`ord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`ord` (
  `ord_number` INT(11) NOT NULL AUTO_INCREMENT,
  `Customer_ID` VARCHAR(10) NULL DEFAULT NULL,
  `Descrip` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Start_Date` DATE NULL DEFAULT NULL,
  `End_Date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ord_number`),
  INDEX `Customer_ID` (`Customer_ID` ASC) VISIBLE,
  CONSTRAINT `ord_ibfk_1`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `workorder`.`CUSTOMER` (`Customer_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`MAKES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`MAKES` (
  `Customer_ID` VARCHAR(10) NOT NULL,
  `Order_No` INT(11) NOT NULL,
  PRIMARY KEY (`Customer_ID`, `Order_No`),
  INDEX `Order_No` (`Order_No` ASC) VISIBLE,
  CONSTRAINT `MAKES_ibfk_2`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `workorder`.`CUSTOMER` (`Customer_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MAKES_ibfk_3`
    FOREIGN KEY (`Order_No`)
    REFERENCES `workorder`.`ord` (`ord_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`POLISHING_STATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`POLISHING_STATION` (
  `Station_ID` INT(11) NOT NULL,
  `edge_type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Station_ID`, `edge_type`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`PROCESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`PROCESS` (
  `Process_ID` INT(11) NOT NULL,
  `Station_ID` INT(11) NULL DEFAULT NULL,
  `Start_Date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Process_ID`),
  INDEX `Station_ID` (`Station_ID` ASC) VISIBLE,
  CONSTRAINT `PROCESS_ibfk_2`
    FOREIGN KEY (`Station_ID`)
    REFERENCES `workorder`.`WORKSTATION` (`Station_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`PROCESSED`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`PROCESSED` (
  `Process_ID` INT(11) NOT NULL,
  `Station_ID` INT(11) NOT NULL,
  `End_Date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Station_ID`, `Process_ID`),
  INDEX `Process_ID` (`Process_ID` ASC) VISIBLE,
  CONSTRAINT `PROCESSED_ibfk_1`
    FOREIGN KEY (`Station_ID`)
    REFERENCES `workorder`.`WORKSTATION` (`Station_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PROCESSED_ibfk_2`
    FOREIGN KEY (`Process_ID`)
    REFERENCES `workorder`.`PROCESS` (`Process_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`PROGRESS_UPDATE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`PROGRESS_UPDATE` (
  `Process_ID` INT(11) NOT NULL,
  `Order_No` INT(11) NOT NULL,
  PRIMARY KEY (`Process_ID`, `Order_No`),
  INDEX `Order_No` (`Order_No` ASC) VISIBLE,
  CONSTRAINT `PROGRESS_UPDATE_ibfk_1`
    FOREIGN KEY (`Process_ID`)
    REFERENCES `workorder`.`PROCESS` (`Process_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PROGRESS_UPDATE_ibfk_3`
    FOREIGN KEY (`Order_No`)
    REFERENCES `workorder`.`ord` (`ord_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PROGRESS_UPDATE_ibfk_4`
    FOREIGN KEY (`Order_No`)
    REFERENCES `workorder`.`ord` (`ord_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`Report_Station_ID`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`Report_Station_ID` (
  `Report_ID` INT(11) NULL DEFAULT NULL,
  `Station_ID` INT(11) NULL DEFAULT NULL,
  INDEX `Report_ID` (`Report_ID` ASC) VISIBLE,
  INDEX `Station_ID` (`Station_ID` ASC) VISIBLE,
  CONSTRAINT `Report_Station_ID_ibfk_1`
    FOREIGN KEY (`Report_ID`)
    REFERENCES `workorder`.`REPORT` (`Report_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Report_Station_ID_ibfk_2`
    FOREIGN KEY (`Station_ID`)
    REFERENCES `workorder`.`WORKSTATION` (`Station_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`STATUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`STATUS` (
  `Station_ID` INT(11) NOT NULL,
  `Completion_Date` DATE NULL DEFAULT NULL,
  `Order_No` INT(11) NOT NULL,
  PRIMARY KEY (`Station_ID`, `Order_No`),
  INDEX `Order_No` (`Order_No` ASC) VISIBLE,
  CONSTRAINT `STATUS_ibfk_2`
    FOREIGN KEY (`Station_ID`)
    REFERENCES `workorder`.`WORKSTATION` (`Station_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `STATUS_ibfk_3`
    FOREIGN KEY (`Order_No`)
    REFERENCES `workorder`.`ord` (`ord_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`SUPERVISE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`SUPERVISE` (
  `E_ID` VARCHAR(10) NOT NULL,
  `M_ID` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`E_ID`, `M_ID`),
  INDEX `M_ID` (`M_ID` ASC) VISIBLE,
  CONSTRAINT `SUPERVISE_ibfk_3`
    FOREIGN KEY (`M_ID`)
    REFERENCES `workorder`.`MANAGER` (`ID_NO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SUPERVISE_ibfk_4`
    FOREIGN KEY (`E_ID`)
    REFERENCES `workorder`.`EMPLOYEE` (`ID_NO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`TRACK_ORDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`TRACK_ORDER` (
  `Order_ID` INT(11) NOT NULL,
  `Station_ID` INT(11) NOT NULL,
  PRIMARY KEY (`Station_ID`, `Order_ID`),
  INDEX `Order_ID` (`Order_ID` ASC) VISIBLE,
  CONSTRAINT `TRACK_ORDER_ibfk_1`
    FOREIGN KEY (`Station_ID`)
    REFERENCES `workorder`.`WORKSTATION` (`Station_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `TRACK_ORDER_ibfk_2`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `workorder`.`ord` (`ord_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `workorder`.`WORK_TO_BE_DONE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workorder`.`WORK_TO_BE_DONE` (
  `Process_ID` INT(11) NOT NULL,
  `Station_ID` INT(11) NOT NULL,
  PRIMARY KEY (`Station_ID`, `Process_ID`),
  INDEX `Process_ID` (`Process_ID` ASC) VISIBLE,
  CONSTRAINT `WORK_TO_BE_DONE_ibfk_1`
    FOREIGN KEY (`Station_ID`)
    REFERENCES `workorder`.`WORKSTATION` (`Station_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `WORK_TO_BE_DONE_ibfk_2`
    FOREIGN KEY (`Process_ID`)
    REFERENCES `workorder`.`PROCESS` (`Process_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;
-- --
-- Insert in a manager
-- --
INSERT INTO manager (`ID_NO`, `Mname`) values (1, 'Dave');
-- --
-- Insert in the employee
-- --
insert into employee (ID_NO, SIN, Name) values ('1000', 200900700, 'Joe');
insert into employee (ID_NO, SIN, Name) values ('1100', 226900700,'Jimmin');
insert into employee (ID_NO, SIN, Name) values ('1110', 226988700,'Caeser');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
